// biome-ignore lint/style/useImportType: Constants used in typeof
import {
  NOTIFICATION_DEFAULT_POSITION,
  NOTIFICATION_EVENT_TOAST,
  NOTIFICATION_TOAST_DURATION_MS,
  NOTIFICATION_VARIANT_ERROR,
  NOTIFICATION_VARIANT_INFO,
  NOTIFICATION_VARIANT_SUCCESS,
  NOTIFICATION_VARIANT_WARNING,
} from '../app/constants'

export type NotificationVariant =
  | typeof NOTIFICATION_VARIANT_INFO
  | typeof NOTIFICATION_VARIANT_SUCCESS
  | typeof NOTIFICATION_VARIANT_WARNING
  | typeof NOTIFICATION_VARIANT_ERROR

export type ToastNotificationPayload = {
  id?: string
  titleKey: string
  message?: string
  descriptionKey?: string
  variant?: NotificationVariant
}

export const DEFAULT_NOTIFICATION_VARIANT: NotificationVariant = NOTIFICATION_VARIANT_INFO
export const DEFAULT_NOTIFICATION_EVENT = NOTIFICATION_EVENT_TOAST
export const DEFAULT_NOTIFICATION_DURATION = NOTIFICATION_TOAST_DURATION_MS
export const DEFAULT_NOTIFICATION_POSITION = NOTIFICATION_DEFAULT_POSITION
export const NOTIFICATION_DISMISS_RETRY_WHEN_MODAL_OPEN_MS = 1_000 as const
export const NOTIFICATION_PORTAL_Z_INDEX = 2_000 as const
export const NOTIFICATION_ALERT_MAX_WIDTH = '56rem' as const
